/*
 * generated by Xtext
 */
package org.eclipse.ocl.examples.xtext.base.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MarkupUiModule extends org.eclipse.ocl.examples.xtext.base.ui.AbstractMarkupUiModule {
	public MarkupUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
