/*
* generated by Xtext
*/
package org.eclipse.ocl.examples.xtext.base.ui.contentassist;

import org.eclipse.ocl.examples.xtext.base.ui.contentassist.AbstractMarkupProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MarkupProposalProvider extends AbstractMarkupProposalProvider {

}
