/*
* generated by Xtext
*/
package org.omg.ocl.markup.ui.contentassist;

import org.omg.ocl.markup.ui.contentassist.AbstractMarkupProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MarkupProposalProvider extends AbstractMarkupProposalProvider {

}
