/*
* generated by Xtext
*/
package org.omg.ocl.markup.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MarkupOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
