/*
* generated by Xtext
*/

package org.eclipse.ocl.examples.xtext.markup.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;


@Singleton
public class MarkupGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class MarkupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Markup");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsMarkupElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Markup:
		//	elements+=MarkupElement*;
		public ParserRule getRule() { return rule; }

		//elements+=MarkupElement*
		public Assignment getElementsAssignment() { return cElementsAssignment; }

		//MarkupElement
		public RuleCall getElementsMarkupElementParserRuleCall_0() { return cElementsMarkupElementParserRuleCall_0; }
	}

	public class MarkupElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MarkupElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFontElementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cNewLineElementParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTextElementParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFigElementParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cFigRefElementParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//MarkupElement:
		//	FontElement | NewLineElement | TextElement | FigElement | FigRefElement;
		public ParserRule getRule() { return rule; }

		//FontElement | NewLineElement | TextElement | FigElement | FigRefElement
		public Alternatives getAlternatives() { return cAlternatives; }

		//FontElement
		public RuleCall getFontElementParserRuleCall_0() { return cFontElementParserRuleCall_0; }

		//NewLineElement
		public RuleCall getNewLineElementParserRuleCall_1() { return cNewLineElementParserRuleCall_1; }

		//TextElement
		public RuleCall getTextElementParserRuleCall_2() { return cTextElementParserRuleCall_2; }

		//FigElement
		public RuleCall getFigElementParserRuleCall_3() { return cFigElementParserRuleCall_3; }

		//FigRefElement
		public RuleCall getFigRefElementParserRuleCall_4() { return cFigRefElementParserRuleCall_4; }
	}

	public class TextElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TextElement");
		private final Assignment cTextAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cTextAlternatives_0 = (Alternatives)cTextAssignment.eContents().get(0);
		private final RuleCall cTextIDTerminalRuleCall_0_0 = (RuleCall)cTextAlternatives_0.eContents().get(0);
		private final RuleCall cTextWORDTerminalRuleCall_0_1 = (RuleCall)cTextAlternatives_0.eContents().get(1);
		private final RuleCall cTextWSTerminalRuleCall_0_2 = (RuleCall)cTextAlternatives_0.eContents().get(2);
		
		//TextElement:
		//	text+=(ID | WORD | WS)+;
		public ParserRule getRule() { return rule; }

		//text+=(ID | WORD | WS)+
		public Assignment getTextAssignment() { return cTextAssignment; }

		//ID | WORD | WS
		public Alternatives getTextAlternatives_0() { return cTextAlternatives_0; }

		//ID
		public RuleCall getTextIDTerminalRuleCall_0_0() { return cTextIDTerminalRuleCall_0_0; }

		//WORD
		public RuleCall getTextWORDTerminalRuleCall_0_1() { return cTextWORDTerminalRuleCall_0_1; }

		//WS
		public RuleCall getTextWSTerminalRuleCall_0_2() { return cTextWSTerminalRuleCall_0_2; }
	}

	public class NewLineElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NewLineElement");
		private final Assignment cTextAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTextNLTerminalRuleCall_0 = (RuleCall)cTextAssignment.eContents().get(0);
		
		//NewLineElement:
		//	text=NL;
		public ParserRule getRule() { return rule; }

		//text=NL
		public Assignment getTextAssignment() { return cTextAssignment; }

		//NL
		public RuleCall getTextNLTerminalRuleCall_0() { return cTextNLTerminalRuleCall_0; }
	}

	public class FontElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FontElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFontAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cFontAlternatives_0_0 = (Alternatives)cFontAssignment_0.eContents().get(0);
		private final Keyword cFontBKeyword_0_0_0 = (Keyword)cFontAlternatives_0_0.eContents().get(0);
		private final Keyword cFontEKeyword_0_0_1 = (Keyword)cFontAlternatives_0_0.eContents().get(1);
		private final Assignment cElementsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementsMarkupElementParserRuleCall_1_0 = (RuleCall)cElementsAssignment_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//FontElement:
		//	font=("b[" | "e[") elements+=MarkupElement* "]";
		public ParserRule getRule() { return rule; }

		//font=("b[" | "e[") elements+=MarkupElement* "]"
		public Group getGroup() { return cGroup; }

		//font=("b[" | "e[")
		public Assignment getFontAssignment_0() { return cFontAssignment_0; }

		//"b[" | "e["
		public Alternatives getFontAlternatives_0_0() { return cFontAlternatives_0_0; }

		//"b["
		public Keyword getFontBKeyword_0_0_0() { return cFontBKeyword_0_0_0; }

		//"e["
		public Keyword getFontEKeyword_0_0_1() { return cFontEKeyword_0_0_1; }

		//elements+=MarkupElement*
		public Assignment getElementsAssignment_1() { return cElementsAssignment_1; }

		//MarkupElement
		public RuleCall getElementsMarkupElementParserRuleCall_1_0() { return cElementsMarkupElementParserRuleCall_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2() { return cRightSquareBracketKeyword_2; }
	}

	public class FigElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FigElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cFigKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Group cGroup_0_1 = (Group)cAlternatives_0.eContents().get(1);
		private final Keyword cFigKeyword_0_1_0 = (Keyword)cGroup_0_1.eContents().get(0);
		private final Assignment cIdAssignment_0_1_1 = (Assignment)cGroup_0_1.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_0_1_1_0 = (RuleCall)cIdAssignment_0_1_1.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_0_1_2 = (Keyword)cGroup_0_1.eContents().get(2);
		private final Assignment cSrcAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSrcSTRINGTerminalRuleCall_1_0 = (RuleCall)cSrcAssignment_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//FigElement:
		//	("fig[" | "fig:" id=ID "[") src=STRING "]";
		public ParserRule getRule() { return rule; }

		//("fig[" | "fig:" id=ID "[") src=STRING "]"
		public Group getGroup() { return cGroup; }

		//"fig[" | "fig:" id=ID "["
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//"fig["
		public Keyword getFigKeyword_0_0() { return cFigKeyword_0_0; }

		//"fig:" id=ID "["
		public Group getGroup_0_1() { return cGroup_0_1; }

		//"fig:"
		public Keyword getFigKeyword_0_1_0() { return cFigKeyword_0_1_0; }

		//id=ID
		public Assignment getIdAssignment_0_1_1() { return cIdAssignment_0_1_1; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_0_1_1_0() { return cIdIDTerminalRuleCall_0_1_1_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_0_1_2() { return cLeftSquareBracketKeyword_0_1_2; }

		//src=STRING
		public Assignment getSrcAssignment_1() { return cSrcAssignment_1; }

		//STRING
		public RuleCall getSrcSTRINGTerminalRuleCall_1_0() { return cSrcSTRINGTerminalRuleCall_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2() { return cRightSquareBracketKeyword_2; }
	}

	public class FigRefElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FigRefElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFigKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRefAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cRefFigElementCrossReference_1_0 = (CrossReference)cRefAssignment_1.eContents().get(0);
		private final RuleCall cRefFigElementIDTerminalRuleCall_1_0_1 = (RuleCall)cRefFigElementCrossReference_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//FigRefElement:
		//	"fig-[" ref=[FigElement] "]";
		public ParserRule getRule() { return rule; }

		//"fig-[" ref=[FigElement] "]"
		public Group getGroup() { return cGroup; }

		//"fig-["
		public Keyword getFigKeyword_0() { return cFigKeyword_0; }

		//ref=[FigElement]
		public Assignment getRefAssignment_1() { return cRefAssignment_1; }

		//[FigElement]
		public CrossReference getRefFigElementCrossReference_1_0() { return cRefFigElementCrossReference_1_0; }

		//ID
		public RuleCall getRefFigElementIDTerminalRuleCall_1_0_1() { return cRefFigElementIDTerminalRuleCall_1_0_1; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2() { return cRightSquareBracketKeyword_2; }
	}
	
	
	private MarkupElements pMarkup;
	private MarkupElementElements pMarkupElement;
	private TextElementElements pTextElement;
	private NewLineElementElements pNewLineElement;
	private FontElementElements pFontElement;
	private FigElementElements pFigElement;
	private FigRefElementElements pFigRefElement;
	private TerminalRule tID;
	private TerminalRule tWORD;
	private TerminalRule tSTRING;
	private TerminalRule tTEXT;
	private TerminalRule tNL;
	private TerminalRule tWS;
	private TerminalRule tANY_OTHER;
	
	private final GrammarProvider grammarProvider;

	@Inject
	public MarkupGrammarAccess(GrammarProvider grammarProvider) {
		this.grammarProvider = grammarProvider;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	
	//Markup:
	//	elements+=MarkupElement*;
	public MarkupElements getMarkupAccess() {
		return (pMarkup != null) ? pMarkup : (pMarkup = new MarkupElements());
	}
	
	public ParserRule getMarkupRule() {
		return getMarkupAccess().getRule();
	}

	//MarkupElement:
	//	FontElement | NewLineElement | TextElement | FigElement | FigRefElement;
	public MarkupElementElements getMarkupElementAccess() {
		return (pMarkupElement != null) ? pMarkupElement : (pMarkupElement = new MarkupElementElements());
	}
	
	public ParserRule getMarkupElementRule() {
		return getMarkupElementAccess().getRule();
	}

	//TextElement:
	//	text+=(ID | WORD | WS)+;
	public TextElementElements getTextElementAccess() {
		return (pTextElement != null) ? pTextElement : (pTextElement = new TextElementElements());
	}
	
	public ParserRule getTextElementRule() {
		return getTextElementAccess().getRule();
	}

	//NewLineElement:
	//	text=NL;
	public NewLineElementElements getNewLineElementAccess() {
		return (pNewLineElement != null) ? pNewLineElement : (pNewLineElement = new NewLineElementElements());
	}
	
	public ParserRule getNewLineElementRule() {
		return getNewLineElementAccess().getRule();
	}

	//FontElement:
	//	font=("b[" | "e[") elements+=MarkupElement* "]";
	public FontElementElements getFontElementAccess() {
		return (pFontElement != null) ? pFontElement : (pFontElement = new FontElementElements());
	}
	
	public ParserRule getFontElementRule() {
		return getFontElementAccess().getRule();
	}

	//FigElement:
	//	("fig[" | "fig:" id=ID "[") src=STRING "]";
	public FigElementElements getFigElementAccess() {
		return (pFigElement != null) ? pFigElement : (pFigElement = new FigElementElements());
	}
	
	public ParserRule getFigElementRule() {
		return getFigElementAccess().getRule();
	}

	//FigRefElement:
	//	"fig-[" ref=[FigElement] "]";
	public FigRefElementElements getFigRefElementAccess() {
		return (pFigRefElement != null) ? pFigRefElement : (pFigRefElement = new FigRefElementElements());
	}
	
	public ParserRule getFigRefElementRule() {
		return getFigRefElementAccess().getRule();
	}

	////terminal INT returns ecore::EInt: ('0'..'9')+;
	//terminal ID:
	//	("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return (tID != null) ? tID : (tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ID"));
	} 

	//terminal WORD:
	//	("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\" | "<" | ">" | "[" | "]") | !("\\" | "[" | "]" | " " | "\t" |
	//	"\n" | "\r"))+;
	public TerminalRule getWORDRule() {
		return (tWORD != null) ? tWORD : (tWORD = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WORD"));
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\" | "<" | ">") | !("\\" | "\""))* "\"";
	public TerminalRule getSTRINGRule() {
		return (tSTRING != null) ? tSTRING : (tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "STRING"));
	} 

	//terminal TEXT:
	//	"\'" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\" | "[" | "]") | !("\\" | "\'" | "[" | "]" | "\n"))* "\'";
	public TerminalRule getTEXTRule() {
		return (tTEXT != null) ? tTEXT : (tTEXT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TEXT"));
	} 

	//terminal NL:
	//	("\n" | "\r") (WS* ("\n" | "\r"))*;
	public TerminalRule getNLRule() {
		return (tNL != null) ? tNL : (tNL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NL"));
	} 

	//terminal WS:
	//	(" " | "\t")+;
	public TerminalRule getWSRule() {
		return (tWS != null) ? tWS : (tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WS"));
	} 

	//// section2/3/4
	//// sec-ref
	//// bullets
	//// fig-ref
	//// fig:name + cap
	//// emphasized-ocl
	//// normal-ocl terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return (tANY_OTHER != null) ? tANY_OTHER : (tANY_OTHER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ANY_OTHER"));
	} 
}
